import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
// import "./globals.css";
import '@/styles/commons.css';
import '@/styles/travel.css';
import '@/styles/rental.css';
import "@fortawesome/fontawesome-free/css/all.min.css";

import "@/styles/travel.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <Script
            src="//dapi.kakao.com/v2/maps/sdk.js?appkey=13052c0aa951d8be4109ba36bf555930&autoload=false"
            strategy="beforeInteractive" // 페이지 렌더 전에 로드
        />
      </body>
    </html>
  );
}
